{% set name = "sqlite-utils" %}
{% set version = "3.38" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1ae77b931384052205a15478d429464f6c67a3ac3b4eafd3c674ac900f623aab

build:
  entry_points:
    - sqlite-utils = sqlite_utils.cli:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - click
    - click-default-group >=1.2.3
    - pluggy
    - python-dateutil
    - sqlite-fts4
    - tabulate

test:
  source_files:
    - tests
  imports:
    - sqlite_utils
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k 'not commands_are_documented and not recipes_are_documented and not insert_streaming_batch_size_1 and not cli_bulk_batch_size' tests
  requires:
    - cogapp
    - hypothesis
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/simonw/sqlite-utils
  summary: CLI tool and Python utility functions for manipulating SQLite databases
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - simonw
    - thewchan
